name: ci

on:
  push:
  pull_request:

env:
  _R_CHECK_FORCE_SUGGESTS_: "false"

jobs:
  r-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup
        uses: eddelbuettel/github-actions/r-ci@master

      - name: Dependencies
        run: ./run.sh install_r tinytest

      - name: Build
        run: R CMD build r-pkg

      - name: Check
        run: R CMD check rapt_*.tar.gz --no-manual

      - name: Test
        run: |
          R CMD INSTALL rapt_*.tar.gz
          Rscript -e 'tinytest::test_package("rapt")'

  daemon:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Build daemon
        run: make -C daemon

      - name: Check daemon runs
        run: |
          ./daemon/raptd --help || true
          file ./daemon/raptd
